services:
  demo-energy-market:
    image: integritee-cli:dev
    container_name: integritee-energy-market-demo
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-client
    depends_on:
      integritee-node:
        condition: service_healthy
      integritee-worker-1:
        condition: service_healthy
    environment:
      - RUST_LOG=warn,ws=warn,itc_rpc_client=warn,ita_stf=debug
    networks:
      - integritee-test-network
    entrypoint:
      "/usr/local/worker-cli/demo_energy_market.sh
      -p 9912 -u ws://integritee-node
      -V wss://integritee-worker-1 -A 2011
      -C /usr/local/bin/integritee-cli
      -I actor_1
      -O /usr/local/worker-cli/orders/order_20_users.json
      -T 2023-03-04T05:06:07+00:00
       2>&1"
    restart: "no"
networks:
  integritee-test-network:
    driver: bridge
